"""Additional practice problems (5 per topic) authored for the CHEM 139 OER.

All problems are original. Numerical data are drawn from public IUPAC 2021 /
NIST / CODATA values, which are uncopyrightable facts.
"""

PROBLEMS = {
    "01": {
        "On the Scientific Method (Section 1.4)": [
            ("Classify as fact, law, hypothesis, or theory: “Iron expands when heated.”",
             "Solution: A general statement summarizing observed behavior across many trials, with no causal explanation → scientific law (a special case of thermal expansion)."),
            ("Classify: “The Sun rose in the east this morning.”",
             "Solution: A single specific observation made at a particular time → fact."),
            ("A student proposes: “If I add NaCl to ice water, the freezing point will drop.” Identify the proposal type and the testable prediction.",
             "Solution: This is a hypothesis. The testable prediction is that the measured freezing point of the salted ice water will be below 0.00 °C and will decrease as more salt is added."),
            ("Why is the statement “Electrons are very small” not, by itself, a scientific hypothesis?",
             "Solution: It is not falsifiable as written — it gives no quantitative claim that experiment could refute. A hypothesis must make a risky, testable prediction (e.g., “The electron mass is about 9.1 × 10⁻³¹ kg”)."),
            ("Distinguish a scientific theory from a scientific law using kinetic-molecular theory and Boyle’s law as examples.",
             "Solution: Boyle’s law summarizes that, at constant T, the product PV is constant for a fixed amount of gas — a pattern (law). Kinetic-molecular theory explains *why*: gas particles in random motion collide with the walls; halving the volume doubles the collision frequency, doubling the pressure (theory)."),
        ],
        "Exact vs. Inexact Numbers (Section 1.8)": [
            ("Classify each: (a) 1 dozen = 12, (b) 1 mile = 1609.344 m (defined), (c) the mass of a textbook measured on a scale.",
             "Solution: (a) exact (counting/definition); (b) exact (defined conversion); (c) inexact (measured)."),
            ("A student counts 24 test tubes in a rack and weighs each on a balance. Which numbers are exact and which are inexact?",
             "Solution: The count “24” is exact (a count of discrete objects). Each measured mass is inexact (limited by the balance’s resolution and accuracy)."),
            ("Why is the conversion factor 100 cm = 1 m exact, but the conversion factor 1 inch = 2.54 cm also exact?",
             "Solution: Both are defined relationships. “100 cm in 1 m” is built into the SI definition; “1 in = 2.54 cm” was defined exactly in 1959 by international agreement, so it is treated as having infinite sig figs."),
            ("A pi value of 3.14159265 is used to compute a circle’s area from a measured radius of 5.2 cm. Which limits the result?",
             "Solution: The measured radius limits the result to 2 sig figs. π is a mathematical constant (treated as exact); the measurement governs uncertainty."),
            ("In the equation v = d/t, if d = 12.50 m (measured) and t = 4.0 s (measured) and the divisor 2 (in finding average) is a counted exact number, which numbers limit the sig figs of the answer?",
             "Solution: Only measured numbers limit precision. d has 4 sig figs, t has 2 sig figs; the answer is limited to 2 sig figs by t. The exact “2” does not limit precision."),
        ],
        "Accuracy and Precision (Section 1.9)": [
            ("Three masses of a 10.000-g standard are recorded: 9.998, 9.999, 10.001 g. Comment on accuracy and precision.",
             "Solution: Mean = 9.999 g; deviation from true value ≤ 0.002 g. Both accurate (close to 10.000 g) and precise (small spread)."),
            ("A sequence of pH measurements gives 4.20, 6.85, 5.10. Comment on accuracy and precision (no true value given).",
             "Solution: With no reference value, accuracy cannot be assessed. The wide spread (range 2.65) indicates poor precision — either the instrument is unstable or the technique is inconsistent."),
            ("A student reports a density of 1.0000 g/mL for water at 4 °C using a balance that reads to 0.001 g and a 100 mL graduated cylinder. Comment on the reported precision.",
             "Solution: The graduated cylinder typically reads to ±0.5 mL, limiting precision to 2–3 sig figs. Reporting 5 sig figs (1.0000) overstates precision; a more honest value is 1.00 g/mL."),
            ("Distinguish random from systematic error and give an example of each in a titration.",
             "Solution: Random error is the unpredictable scatter from one trial to the next (e.g., reading the meniscus slightly differently each time). Systematic error is a consistent bias (e.g., the buret is miscalibrated, so every titration reads 0.05 mL too high)."),
            ("A balance is zeroed correctly but its readout is truncated to whole grams. Are repeated readings of a 4.7 g object accurate, precise, or both?",
             "Solution: Every reading will be “4 g” — highly precise (no scatter) but inaccurate (true value 4.7 g; the bias is about 0.7 g). The readings are precise but inaccurate."),
        ],
        "Counting Significant Figures (Section 1.11)": [
            ("How many sig figs in 4002?",
             "Solution: 4 sig figs. Captive zeros are always significant."),
            ("How many sig figs in 0.00500?",
             "Solution: 3 sig figs. Leading zeros do not count; the captive 0 and trailing 0 (after a decimal point) do."),
            ("How many sig figs in 1.20 × 10³?",
             "Solution: 3 sig figs. All digits in the coefficient are significant."),
            ("How many sig figs in 100. (with explicit decimal point)?",
             "Solution: 3 sig figs. The decimal point makes the trailing zeros significant."),
            ("How many sig figs in 600?",
             "Solution: Ambiguous (1 to 3). Without a decimal point or scientific notation, trailing zeros’ significance is unclear. Express as 6 × 10², 6.0 × 10², or 6.00 × 10² to remove ambiguity."),
        ],
        "Arithmetic with Significant Figures (Section 1.12)": [
            ("Compute 25.32 cm + 1.5 cm + 0.044 cm with correct sig figs.",
             "Solution: 25.32 + 1.5 + 0.044 = 26.864; round to the least precise decimal place (1.5 has 1 decimal place) → 26.9 cm."),
            ("Compute 7.50 g ÷ 2.5 mL with correct sig figs.",
             "Solution: 7.50 / 2.5 = 3.00; the divisor (2.5) has 2 sig figs, so report 3.0 g/mL."),
            ("Compute (3.75 cm)(2.0 cm)(4.50 cm) with correct sig figs.",
             "Solution: 3.75 × 2.0 × 4.50 = 33.75; limit by 2.0 (2 sig figs) → 34 cm³."),
            ("A student measures three replicate masses: 12.34 g, 12.36 g, 12.35 g. Compute the mean to the correct sig figs.",
             "Solution: Sum = 37.05 g; divide by exact 3 → 12.35 g. Each measurement has 4 sig figs and 2 decimal places; the answer keeps 2 decimal places → 12.35 g."),
            ("Compute (0.0250 mol)(98.08 g/mol) with correct sig figs.",
             "Solution: 0.0250 × 98.08 = 2.452; limit by 0.0250 (3 sig figs) → 2.45 g."),
        ],
        "Scientific Notation (Sections 1.13–1.14)": [
            ("Convert 0.00038 to scientific notation.",
             "Solution: 3.8 × 10⁻⁴."),
            ("Convert 4.20 × 10² to ordinary decimal form.",
             "Solution: 420."),
            ("Compute (3.0 × 10⁶)(2.0 × 10⁻³) in scientific notation with correct sig figs.",
             "Solution: 6.0 × 10³."),
            ("Compute (9.6 × 10⁻²) ÷ (3.2 × 10²) in scientific notation with correct sig figs.",
             "Solution: 3.0 × 10⁻⁴."),
            ("Compute (4.5 × 10⁴) + (2.5 × 10³) in scientific notation with correct sig figs.",
             "Solution: 4.5 × 10⁴ + 0.25 × 10⁴ = 4.75 × 10⁴; round to the precision of 4.5 (1 decimal place in the coefficient) → 4.8 × 10⁴."),
        ],
    },

    "02": {
        "Metric Units and Prefixes (Sections 2.1–2.4)": [
            ("Convert 2.50 km to meters.",
             "Solution: 2.50 km × (1000 m / 1 km) = 2.50 × 10³ m = 2500 m."),
            ("Convert 75 mg to grams.",
             "Solution: 75 mg × (1 g / 1000 mg) = 0.075 g."),
            ("Convert 0.045 L to mL.",
             "Solution: 0.045 L × (1000 mL / 1 L) = 45 mL."),
            ("Convert 3.2 μg to mg.",
             "Solution: 3.2 μg × (1 mg / 1000 μg) = 0.0032 mg = 3.2 × 10⁻³ mg."),
            ("List the prefixes for: 10³, 10⁻², 10⁻³, 10⁻⁶, 10⁻⁹.",
             "Solution: kilo (k), centi (c), milli (m), micro (μ), nano (n)."),
        ],
        "Conversion Factors and Dimensional Analysis (Sections 2.6–2.7)": [
            ("Convert 4.0 ft to centimeters. (1 in = 2.54 cm exact; 12 in = 1 ft exact.)",
             "Solution: 4.0 ft × (12 in / 1 ft) × (2.54 cm / 1 in) = 121.92 cm → 1.2 × 10² cm (2 sig figs)."),
            ("A car travels 65 mi/h. Convert to m/s. (1 mi = 1.609 km.)",
             "Solution: 65 mi/h × (1.609 km / 1 mi) × (1000 m / 1 km) × (1 h / 3600 s) = 29.05 m/s → 29 m/s (2 sig figs)."),
            ("How many milliliters in 2.0 gallons? (1 gal = 3.785 L.)",
             "Solution: 2.0 gal × (3.785 L / 1 gal) × (1000 mL / 1 L) = 7570 mL → 7.6 × 10³ mL (2 sig figs)."),
            ("Convert 250 mg to ounces (oz). (1 lb = 453.6 g; 1 lb = 16 oz exact.)",
             "Solution: 250 mg × (1 g / 1000 mg) × (1 lb / 453.6 g) × (16 oz / 1 lb) = 0.00882 oz → 8.8 × 10⁻³ oz."),
            ("A patient is given 0.50 L of saline. How many quarts is that? (1 L = 1.057 qt.)",
             "Solution: 0.50 L × (1.057 qt / 1 L) = 0.53 qt (2 sig figs)."),
        ],
        "Density (Section 2.8)": [
            ("A metal cube of edge 2.50 cm has mass 78.4 g. Compute density.",
             "Solution: V = (2.50 cm)³ = 15.625 cm³; ρ = 78.4/15.625 = 5.02 g/cm³."),
            ("What mass of mercury (ρ = 13.6 g/mL) fills a 25.0 mL flask?",
             "Solution: m = ρV = 13.6 g/mL × 25.0 mL = 340. g."),
            ("A 50.0 g sample of an unknown liquid has volume 63.3 mL. Identify it from: water (1.00), ethanol (0.789), acetone (0.791).",
             "Solution: ρ = 50.0/63.3 = 0.790 g/mL. Matches ethanol or acetone within reading; further testing needed (e.g., boiling point) to distinguish."),
            ("A piece of aluminum (ρ = 2.70 g/cm³) has mass 8.10 g. What is its volume?",
             "Solution: V = m/ρ = 8.10/2.70 = 3.00 cm³."),
            ("Will a piece of iron (ρ = 7.87 g/cm³) sink or float in mercury (ρ = 13.6 g/cm³)?",
             "Solution: Float. An object of lower density than the surrounding fluid floats."),
        ],
        "Equivalence and Dosage Factors (Section 2.9)": [
            ("A drug is dosed at 5.0 mg per kg of body mass. What dose is required for a 70.0 kg patient?",
             "Solution: 70.0 kg × (5.0 mg / 1 kg) = 350 mg → 3.5 × 10² mg."),
            ("A 250 mg/5 mL liquid medication is prescribed at 500 mg per dose. What volume per dose?",
             "Solution: 500 mg × (5 mL / 250 mg) = 10 mL."),
            ("A patient must receive 1.00 L of IV saline over 8.0 h. What is the drip rate in mL/min?",
             "Solution: 1.00 L × (1000 mL / 1 L) ÷ (8.0 h × 60 min/h) = 1000/480 = 2.08 mL/min → 2.1 mL/min."),
            ("An IV solution contains 0.90% NaCl by mass. How many grams of NaCl in 250.0 mL of solution? (Assume ρ = 1.00 g/mL.)",
             "Solution: Mass of solution = 250.0 g; mass of NaCl = 0.0090 × 250.0 = 2.25 g → 2.3 g (2 sig figs from 0.90%)."),
            ("A child weighs 18 kg. Acetaminophen is dosed at 12 mg/kg every 6 h. The available syrup is 160 mg/5 mL. What volume per dose?",
             "Solution: Dose mass = 18 × 12 = 216 mg; volume = 216 mg × (5 mL / 160 mg) = 6.75 mL → 6.8 mL."),
        ],
        "Percentage and Percent Error (Section 2.10)": [
            ("A measured value is 9.85 g and the accepted value is 10.00 g. Compute percent error.",
             "Solution: %error = |9.85 − 10.00|/10.00 × 100% = 1.50%."),
            ("A 200 g alloy contains 25 g of zinc. Percent zinc by mass?",
             "Solution: 25/200 × 100% = 12.5%."),
            ("A solution is 7.5% glucose by mass. Mass of glucose in 240 g of solution?",
             "Solution: 0.075 × 240 = 18 g."),
            ("A scale reads 5.10 kg for an object whose mass is known to be 5.000 kg. Percent error?",
             "Solution: |5.10 − 5.000|/5.000 × 100% = 2.0%."),
            ("Two students measure a length whose true value is 12.50 cm. Student A reports 12.45 cm; Student B reports 12.62 cm. Which has lower percent error?",
             "Solution: A: |12.45−12.50|/12.50 = 0.40%. B: 0.96%. Student A is more accurate."),
        ],
        "Temperature (Section 2.11)": [
            ("Convert 25 °C to kelvins.",
             "Solution: T = 25 + 273.15 = 298.15 K → 298 K."),
            ("Convert 98.6 °F to °C.",
             "Solution: T_C = (98.6 − 32)/1.8 = 66.6/1.8 = 37.0 °C."),
            ("Convert 350 K to °F.",
             "Solution: T_C = 350 − 273.15 = 76.85 °C; T_F = 1.8(76.85) + 32 = 170.3 °F → 170. °F."),
            ("Liquid nitrogen boils at 77 K. What is this in °C?",
             "Solution: T_C = 77 − 273.15 = −196 °C."),
            ("A thermometer reads 0 °F. What is this in °C and K?",
             "Solution: T_C = (0 − 32)/1.8 = −17.8 °C; T_K = −17.8 + 273.15 = 255 K."),
        ],
    },

    "03": {
        "States and Properties of Matter": [
            ("Identify each as physical or chemical change: (a) ice melting, (b) wood burning, (c) sugar dissolving in water, (d) iron rusting, (e) a balloon being stretched.",
             "Solution: Physical: a, c, e. Chemical: b, d."),
            ("Classify each as intensive or extensive: (a) volume, (b) mass, (c) boiling point, (d) energy released by combustion of a sample, (e) color.",
             "Solution: Intensive: c, e. Extensive: a, b, d."),
            ("At room temperature and 1 atm, give the physical state of: (a) Hg, (b) Cl₂, (c) Cu, (d) H₂O, (e) CO₂.",
             "Solution: Hg liquid, Cl₂ gas, Cu solid, H₂O liquid, CO₂ gas."),
            ("Why does a gas have neither a fixed shape nor a fixed volume?",
             "Solution: At ordinary pressures, gas particles are widely separated and moving rapidly with negligible attractions. They expand to fill any container."),
            ("A solid sublimes when heated at 1 atm. Identify the phase change and give an example.",
             "Solution: Sublimation: solid → gas without passing through the liquid state. Example: dry ice (solid CO₂) at room temperature and 1 atm."),
        ],
        "Pure Substances and Mixtures": [
            ("Classify each: (a) seawater, (b) iron filings + sand, (c) graphite, (d) bronze, (e) carbon dioxide gas.",
             "Solution: (a) homogeneous mixture, (b) heterogeneous mixture, (c) pure element, (d) homogeneous mixture (alloy), (e) pure compound."),
            ("Distinguish a compound from a homogeneous mixture using a single property.",
             "Solution: A compound has a fixed composition by mass and can only be separated by chemical means. A homogeneous mixture has variable composition and can be separated by physical means (distillation, filtration of dissolved species, etc.)."),
            ("A clear liquid distills entirely at 78.4 °C with no temperature change. Pure substance or mixture?",
             "Solution: Pure substance — a sharp, constant boiling point during distillation indicates a single component."),
            ("Identify each as element, compound, homogeneous mixture, or heterogeneous mixture: (a) Cu, (b) NaCl, (c) salt water, (d) chocolate-chip cookie, (e) air.",
             "Solution: (a) element, (b) compound, (c) homogeneous mixture, (d) heterogeneous mixture, (e) homogeneous mixture."),
            ("Sketch a particle-level picture (in words) for: a sample of pure N₂(g), and a sample of N₂(g) mixed with O₂(g).",
             "Solution: Pure N₂: only diatomic N—N pairs, all identical. Mixture: a random distribution of N—N pairs and O—O pairs together; both kinds of molecules present."),
        ],
        "Symbols and Names": [
            ("Give the symbols: tin, lead, antimony, tungsten, silver, sodium, potassium.",
             "Solution: Sn, Pb, Sb, W, Ag, Na, K."),
            ("Give the names: Au, Hg, Fe, Cu, Pt, Pb, Sn.",
             "Solution: gold, mercury, iron, copper, platinum, lead, tin."),
            ("Identify the element with atomic number 17 and give its symbol.",
             "Solution: Chlorine, Cl."),
            ("Identify the element with symbol Mg and give its name and atomic number.",
             "Solution: Magnesium, Z = 12."),
            ("Why does the symbol for sodium come from the Latin word “natrium”? Give one other element whose symbol comes from a non-English root.",
             "Solution: Many element symbols come from older Latin or Greek names used historically. Examples: K (kalium = potassium), Pb (plumbum = lead), Au (aurum = gold), Fe (ferrum = iron)."),
        ],
        "Abundance": [
            ("List, in order of decreasing mass abundance, the four most abundant elements in Earth’s crust.",
             "Solution: O > Si > Al > Fe."),
            ("List, in order of decreasing mass abundance, the four most abundant elements in the human body.",
             "Solution: O > C > H > N."),
            ("Which two elements together account for more than 98% of the mass of the universe?",
             "Solution: Hydrogen and helium."),
            ("The mass abundance of iron in Earth’s crust is about 5%. What mass of iron, in metric tons, is contained in 1.0 × 10⁶ metric tons of crustal rock?",
             "Solution: 0.05 × 1.0 × 10⁶ = 5 × 10⁴ metric tons."),
            ("Why is oxygen the most abundant element in both Earth’s crust and the human body, despite being unrelated origins?",
             "Solution: Oxygen forms strong bonds with most metals and nonmetals. In the crust it is locked into silicates and oxides; in the body it is largely the oxygen in water. Oxygen’s chemistry, not a single source, explains its dominance in both."),
        ],
    },

    "04": {
        "Dalton, Atoms, and Molecules": [
            ("State the four central postulates of Dalton’s atomic theory.",
             "Solution: (1) All matter is composed of atoms. (2) Atoms of a given element are identical in mass and properties. (3) Compounds are formed by combining atoms in fixed whole-number ratios. (4) Atoms are rearranged but neither created nor destroyed in chemical reactions."),
            ("Which of Dalton’s postulates was modified by the discovery of isotopes, and how?",
             "Solution: Postulate 2: atoms of the same element can have slightly different masses (isotopes), though they share chemical properties."),
            ("A compound contains 40.0% S and 60.0% O by mass. Express the mass ratio of S to O in lowest whole-number terms (illustrating the law of definite proportions).",
             "Solution: 40.0/60.0 = 2/3, so the S:O mass ratio is 2:3 in any sample of this compound."),
            ("Two oxides of nitrogen contain 1.00 g N combined with 1.14 g O and 2.28 g O respectively. State the law illustrated.",
             "Solution: The masses of O combining with a fixed mass of N are in the ratio 1.14:2.28 = 1:2 — the law of multiple proportions."),
            ("Distinguish an atom from a molecule, and give one molecular form of an element.",
             "Solution: An atom is the smallest unit of an element. A molecule is two or more atoms bonded covalently. Examples of molecular elements: O₂, N₂, H₂, P₄, S₈."),
        ],
        "Subatomic Particles": [
            ("State the relative charge and approximate relative mass of the proton, neutron, and electron.",
             "Solution: Proton: +1, mass ≈ 1 u. Neutron: 0, mass ≈ 1 u. Electron: −1, mass ≈ 1/1836 u (negligible compared with nucleons)."),
            ("In a neutral atom, what is the relationship between the number of protons and the number of electrons?",
             "Solution: They are equal. The atom has no net charge because the +1 charge of each proton is balanced by a −1 electron."),
            ("How many protons, neutrons, and electrons are in a neutral atom of ⁸¹Br?",
             "Solution: Z = 35 → 35 protons, 35 electrons. A = 81 → N = 81 − 35 = 46 neutrons."),
            ("How many protons, neutrons, and electrons are in a neutral ⁶⁰Co atom?",
             "Solution: Z = 27 → 27 protons, 27 electrons. N = 60 − 27 = 33 neutrons."),
            ("Why is the atom’s mass nearly all in the nucleus?",
             "Solution: The proton and neutron each have ~1 u, while the electron has ~1/1836 u. With Z protons and (A−Z) neutrons in the nucleus and only Z electrons outside, the nuclear mass overwhelmingly dominates."),
        ],
        "Atomic Number, Mass Number, Isotopes": [
            ("Define atomic number and mass number.",
             "Solution: Atomic number Z = number of protons in the nucleus (and identity of the element). Mass number A = total nucleons = Z + N (number of protons + neutrons)."),
            ("Two nuclides have Z = 6 and A values 12 and 14. What is their relationship?",
             "Solution: Both are carbon (Z = 6). ¹²C and ¹⁴C are isotopes of carbon, differing in neutron count (6 vs 8)."),
            ("Write the isotope symbol for an atom with 17 protons and 20 neutrons.",
             "Solution: Z = 17 (Cl), A = 37 → ³⁷Cl (or Cl-37)."),
            ("How many neutrons are in ²³⁸U?",
             "Solution: A − Z = 238 − 92 = 146 neutrons."),
            ("Two atoms have the same Z but different A. Compare their chemical and physical properties.",
             "Solution: Same chemical behavior (same proton/electron count). Slightly different physical properties (mass, density, diffusion rate); for radioactive isotopes, also different nuclear stability."),
        ],
        "Atomic Mass Calculations": [
            ("Element X has two isotopes: X-10 (10.013 u, 19.9% abundance) and X-11 (11.009 u, 80.1%). Compute the standard atomic weight.",
             "Solution: 0.199 × 10.013 + 0.801 × 11.009 = 1.993 + 8.818 = 10.81 u (the value for boron)."),
            ("Chlorine has two isotopes, ³⁵Cl (34.969 u) and ³⁷Cl (36.966 u), with abundances 75.78% and 24.22%. Compute the atomic weight.",
             "Solution: 0.7578 × 34.969 + 0.2422 × 36.966 = 26.499 + 8.953 = 35.45 u."),
            ("Copper has two stable isotopes: ⁶³Cu (62.930 u, 69.17%) and ⁶⁵Cu (64.928 u, 30.83%). Compute the atomic weight.",
             "Solution: 0.6917 × 62.930 + 0.3083 × 64.928 = 43.527 + 20.017 = 63.54 u."),
            ("If element Q has two isotopes Q-23 and Q-25 with abundances 80% and 20%, estimate the atomic weight to 2 sig figs (assume isotope masses equal mass numbers).",
             "Solution: 0.80(23) + 0.20(25) = 18.4 + 5.0 = 23.4 → 23 u."),
            ("The atomic weight of Mg is 24.31 u. Its three isotopes have masses 23.985 u, 24.986 u, and 25.983 u. The lightest is the most abundant. Why is the atomic weight closer to 24 than to 26?",
             "Solution: The atomic weight is the abundance-weighted mean of isotope masses. With ²⁴Mg the most abundant, the mean lies closer to its mass (24.0)."),
        ],
        "Evidence for Subatomic Particles": [
            ("Briefly describe what cathode-ray-tube experiments demonstrated about the electron.",
             "Solution: Cathode rays (1) traveled in straight lines, (2) carried negative charge (deflected by electric and magnetic fields), and (3) were the same regardless of the cathode metal — implying electrons are a universal subatomic particle."),
            ("What did Millikan’s oil-drop experiment determine?",
             "Solution: The charge of the electron (the elementary charge, e ≈ 1.602 × 10⁻¹⁹ C) and, combined with Thomson’s e/m, the electron mass."),
            ("Summarize the unexpected observation in the Geiger–Marsden gold-foil experiment and what Rutherford concluded from it.",
             "Solution: A small fraction of α particles scattered through very large angles, occasionally back toward the source. Rutherford concluded the atom’s positive charge and most of its mass are concentrated in a tiny dense nucleus."),
            ("Before the gold-foil experiment, what model of the atom was widely accepted, and how did the new evidence force its replacement?",
             "Solution: Thomson’s “plum-pudding” model (electrons embedded in a diffuse positive sphere). It could not explain the rare large-angle scattering; only a concentrated nucleus could."),
            ("How did the discovery of the neutron resolve a problem with the proton-only nuclear model?",
             "Solution: Atomic masses were greater than the number of protons would account for, and many isotopes existed. A neutral particle of comparable mass (the neutron) explained both."),
        ],
    },

    "05": {
        "Periodic Law and Periodic Table": [
            ("State the modern periodic law.",
             "Solution: The properties of the elements are periodic functions of their atomic numbers."),
            ("Identify the period and group of: (a) Mg, (b) Br, (c) Fe, (d) Sn, (e) I.",
             "Solution: (a) period 3, group 2; (b) period 4, group 17; (c) period 4, group 8; (d) period 5, group 14; (e) period 5, group 17."),
            ("Identify whether each is a metal, metalloid, or nonmetal: Si, K, S, Ge, Mg, Cl, As.",
             "Solution: Metals: K, Mg. Metalloids: Si, Ge, As. Nonmetals: S, Cl."),
            ("Name the family for each group: 1, 2, 17, 18.",
             "Solution: 1 = alkali metals (excluding H), 2 = alkaline earth metals, 17 = halogens, 18 = noble gases."),
            ("Why are Mendeleev’s gaps in the original periodic table considered a triumph of his approach?",
             "Solution: He left blanks for elements he predicted should exist with specific properties; the later discovery of Ga, Sc, and Ge confirmed his predictions and validated the periodic-law approach."),
        ],
        "Shells, Subshells, Orbitals": [
            ("List the subshells in the n = 3 shell and the number of orbitals in each.",
             "Solution: n = 3 contains 3s (1 orbital), 3p (3), and 3d (5) subshells; total 9 orbitals, 18 electrons capacity."),
            ("How many electrons can fit in the n = 4 shell?",
             "Solution: 4s + 4p + 4d + 4f = 1 + 3 + 5 + 7 = 16 orbitals × 2 electrons each = 32 electrons."),
            ("What is the maximum number of electrons in any single orbital? State the principle.",
             "Solution: 2 electrons (with opposite spins) by the Pauli exclusion principle."),
            ("Identify the subshell labels (s, p, d, f) by the value of the angular-momentum quantum number ℓ.",
             "Solution: ℓ = 0 (s), 1 (p), 2 (d), 3 (f)."),
            ("Sketch the shape (in words) of an s and a p orbital.",
             "Solution: s orbital: spherically symmetric around the nucleus. p orbital: dumbbell shape with two lobes on opposite sides of the nucleus along one axis (px, py, or pz)."),
        ],
        "Electron Configurations": [
            ("Write the ground-state electron configuration of N (Z = 7).",
             "Solution: 1s² 2s² 2p³."),
            ("Write the ground-state electron configuration of Ca (Z = 20).",
             "Solution: 1s² 2s² 2p⁶ 3s² 3p⁶ 4s² (or [Ar] 4s²)."),
            ("Write the noble-gas-shorthand configuration of Br (Z = 35).",
             "Solution: [Ar] 4s² 3d¹⁰ 4p⁵."),
            ("Identify the element whose ground-state configuration is [Ne] 3s² 3p⁴.",
             "Solution: 2 + 8 + 2 + 4 = 16 electrons → Z = 16, sulfur (S)."),
            ("Write the electron configuration of Fe (Z = 26) and identify the number of valence electrons.",
             "Solution: [Ar] 4s² 3d⁶. Fe has 8 outer-shell electrons (4s² 3d⁶) participating in chemistry as transition-metal valence electrons."),
        ],
        "Orbital Diagrams": [
            ("Draw the orbital diagram (in arrows-in-boxes notation, described) for O.",
             "Solution: 1s [↑↓] 2s [↑↓] 2p [↑↓][↑][↑]. Hund’s rule: singly occupy each 2p orbital before pairing."),
            ("How many unpaired electrons in the ground state of P (Z = 15)?",
             "Solution: [Ne] 3s² 3p³ → three unpaired electrons in 3p (one in each 3p orbital)."),
            ("State Hund’s rule.",
             "Solution: Within a degenerate set of orbitals (same energy), electrons occupy separate orbitals with parallel spins before pairing."),
            ("Explain why the ground state of carbon has two unpaired electrons rather than one pair in 2p.",
             "Solution: With two electrons in 2p, Hund’s rule places one in each of two different p orbitals (spins parallel); pairing in a single 2p orbital would cost more energy than occupying two orbitals separately."),
            ("How many unpaired electrons in Fe and Fe²⁺ in their ground states? (Use [Ar] 4s² 3d⁶ for Fe.)",
             "Solution: Fe: 4 unpaired electrons (3d⁶ fills 1 orbital fully and singly occupies the remaining 4). Fe²⁺: lose the 4s electrons first → [Ar] 3d⁶; still 4 unpaired electrons."),
        ],
        "Periodic Trends": [
            ("Rank in order of increasing atomic radius: Na, K, Rb, Cs.",
             "Solution: Na < K < Rb < Cs (radius increases down a group)."),
            ("Rank in order of increasing first ionization energy: Na, Mg, Al.",
             "Solution: Na < Al < Mg. (Mg is anomalously high due to its filled 3s²; Al loses one 3p electron more easily.)"),
            ("Which has greater electronegativity: O or S?",
             "Solution: O. Electronegativity decreases down a group; oxygen sits above sulfur."),
            ("Predict whether atomic radius increases or decreases left-to-right across a period and explain.",
             "Solution: Decreases. Effective nuclear charge grows as Z increases (electrons added to the same shell), pulling the cloud inward."),
            ("Order the radii: Mg, Mg²⁺, O, O²⁻. Explain.",
             "Solution: O²⁻ > O ≈ small change discussion; for the isoelectronic set Mg²⁺, O²⁻ have same 10 electrons but different nuclear charges. Order from smallest to largest: Mg²⁺ < Mg, and Mg²⁺ < O²⁻. Detailed: Mg²⁺ (smallest), then O, then Mg, then O²⁻. (Cations are smaller than the parent atom; anions larger; isoelectronic species shrink as Z increases.)"),
        ],
    },

    "06": {
        "Lewis Symbols, Octet, Ions": [
            ("Draw Lewis symbols (in words: sym + dots) for: Na, Mg, Al, C, N, O, F, Ne.",
             "Solution: Na (1 dot), Mg (2 dots), Al (3 dots), C (4 dots), N (5 dots), O (6 dots), F (7 dots), Ne (8 dots, octet)."),
            ("Predict the most likely ion charge for each: Li, Mg, Al, S, Cl, K.",
             "Solution: Li⁺, Mg²⁺, Al³⁺, S²⁻, Cl⁻, K⁺."),
            ("Why does sodium readily form Na⁺ but not Na²⁺ in chemical compounds?",
             "Solution: Na has one valence electron (3s¹). Removing it gives the noble-gas configuration of Ne; removing a second would require breaking into the very stable filled 2p shell (high IE2)."),
            ("Why does Cl readily form Cl⁻ but not Cl²⁻?",
             "Solution: Cl gains one electron to complete the octet (matching Ar). A second electron would have to enter a higher-energy orbital and faces strong electron–electron repulsion in the already-saturated 3p shell."),
            ("State the octet rule and give one common exception.",
             "Solution: Many main-group atoms gain, lose, or share electrons to reach 8 valence electrons (s²p⁶). Common exceptions: H/He (duet); B and Al (often electron-deficient, 6 valence electrons); P, S, Cl in some compounds (expanded octet)."),
        ],
        "Ionic Formulas": [
            ("Write the formula for the ionic compound of Mg²⁺ and Cl⁻.",
             "Solution: MgCl₂."),
            ("Write the formula for the ionic compound of Al³⁺ and O²⁻.",
             "Solution: Al₂O₃ (cross the charges)."),
            ("Write formulas: (a) potassium iodide, (b) calcium phosphide, (c) sodium nitride, (d) barium fluoride.",
             "Solution: (a) KI, (b) Ca₃P₂, (c) Na₃N, (d) BaF₂."),
            ("What is the formula for the binary compound formed between strontium (Group 2) and bromine?",
             "Solution: SrBr₂."),
            ("Identify the ion charges and write the formula for the compound of Ga³⁺ and S²⁻.",
             "Solution: Ga₂S₃."),
        ],
        "Polyatomic Ions": [
            ("Give the formula and charge of: sulfate, nitrate, carbonate, ammonium, hydroxide.",
             "Solution: SO₄²⁻, NO₃⁻, CO₃²⁻, NH₄⁺, OH⁻."),
            ("Write the formula for the compound formed by Ca²⁺ and PO₄³⁻.",
             "Solution: Ca₃(PO₄)₂."),
            ("Write formulas: (a) ammonium sulfate, (b) sodium phosphate, (c) iron(III) hydroxide.",
             "Solution: (a) (NH₄)₂SO₄, (b) Na₃PO₄, (c) Fe(OH)₃."),
            ("Identify the polyatomic ion in NaHCO₃ and give its name.",
             "Solution: HCO₃⁻, hydrogen carbonate (bicarbonate)."),
            ("Write the formula for aluminum sulfate.",
             "Solution: Al₂(SO₄)₃."),
        ],
        "Lewis Structures": [
            ("Draw the Lewis structure for HF.",
             "Solution: H—F with three lone pairs on F. Total valence electrons: 1 + 7 = 8. Bond uses 2; remaining 6 as 3 lone pairs on F."),
            ("Draw the Lewis structure for CO₂.",
             "Solution: O=C=O with two lone pairs on each O. Total valence electrons: 4 + 12 = 16; 8 in bonds (two double bonds), 8 as four lone pairs."),
            ("Draw the Lewis structure for NH₃.",
             "Solution: H—N—H with another H bonded to N and one lone pair on N. Total: 5 + 3 = 8 valence electrons; 6 in three N—H bonds, 2 as a lone pair on N."),
            ("Draw the Lewis structure for the cyanide ion, CN⁻.",
             "Solution: [:C≡N:]⁻ with one lone pair on C and one on N. Total valence: 4 + 5 + 1 = 10; 6 in the triple bond, 4 as lone pairs."),
            ("Draw the Lewis structure for SO₂ (resonance not required for the question; one structure).",
             "Solution: O=S—O with one lone pair on S, two lone pairs on the double-bonded O, and three lone pairs on the single-bonded O (formal charges: +1 on S? recompute). Total: 6 + 12 = 18 valence; one S=O double, one S—O single; lone pairs allocated to satisfy octets. Resonance structures place the double bond on either oxygen."),
        ],
        "VSEPR Geometry": [
            ("Predict the molecular geometry of CH₄.",
             "Solution: Tetrahedral, ~109.5° bond angles (4 bonding pairs, no lone pairs)."),
            ("Predict the molecular geometry of H₂O.",
             "Solution: Bent (≈ 104.5°). 4 electron groups (2 bonds + 2 lone pairs); electron-pair geometry tetrahedral, molecular shape bent."),
            ("Predict the molecular geometry of NH₃.",
             "Solution: Trigonal pyramidal (≈ 107°). 4 electron groups (3 bonds + 1 lone pair)."),
            ("Predict the molecular geometry of CO₂.",
             "Solution: Linear (180°). 2 electron groups (two double bonds count as one group each)."),
            ("Predict the molecular geometry of BF₃.",
             "Solution: Trigonal planar (120°). 3 bonding pairs, no lone pairs around B (electron-deficient)."),
        ],
        "Electronegativity and Polarity": [
            ("Rank in order of increasing electronegativity: Na, P, Cl, F.",
             "Solution: Na < P < Cl < F."),
            ("Predict whether each bond is nonpolar covalent, polar covalent, or ionic: H—H, H—Cl, Na—Cl, C—O.",
             "Solution: H—H nonpolar covalent (ΔEN = 0). H—Cl polar covalent (ΔEN ≈ 0.96). Na—Cl ionic (ΔEN ≈ 2.1). C—O polar covalent (ΔEN ≈ 0.89)."),
            ("Identify whether CO₂ is polar or nonpolar overall and explain.",
             "Solution: Each C=O bond is polar, but the linear geometry causes the two bond dipoles to cancel. CO₂ is nonpolar overall."),
            ("Identify whether H₂O is polar or nonpolar overall and explain.",
             "Solution: Polar. Each O—H bond is polar, and the bent geometry leaves a net dipole moment."),
            ("Compare polarity of NH₃ vs. NF₃. Both are pyramidal; predict which has the larger dipole moment.",
             "Solution: NH₃ has the larger dipole. In NH₃ the bond dipoles point toward N and add with the lone-pair dipole; in NF₃ the bond dipoles point toward F (away from N) and partially oppose the lone-pair dipole."),
        ],
        "Bond Order": [
            ("State the bond orders in: H—H, O=O, N≡N.",
             "Solution: H—H = 1; O=O = 2; N≡N = 3."),
            ("Rank C—C, C=C, C≡C in order of increasing bond length.",
             "Solution: C≡C < C=C < C—C. Higher bond order = shorter, stronger bond."),
            ("Rank C—C, C=C, C≡C in order of increasing bond energy.",
             "Solution: C—C < C=C < C≡C."),
            ("Predict the bond order in the carbonate ion CO₃²⁻.",
             "Solution: Each C—O bond has bond order 4/3 (≈1.33), the average over three resonance structures with one double and two single bonds."),
            ("In O₃ (ozone), describe the bonding picture using resonance and give the average bond order.",
             "Solution: Two resonance structures place the double bond on either side. The average O—O bond order is 1.5; both bonds are equivalent in the real molecule."),
        ],
    },

    "07": {
        "Type I (Fixed-Charge) Binary Ionic": [
            ("Name: NaCl, KBr, MgO, CaCl₂, Al₂O₃.",
             "Solution: Sodium chloride, potassium bromide, magnesium oxide, calcium chloride, aluminum oxide."),
            ("Write formulas: (a) lithium fluoride, (b) sodium sulfide, (c) magnesium nitride, (d) aluminum chloride, (e) calcium phosphide.",
             "Solution: (a) LiF, (b) Na₂S, (c) Mg₃N₂, (d) AlCl₃, (e) Ca₃P₂."),
            ("Name: BaO, Na₃N, K₂S.",
             "Solution: Barium oxide, sodium nitride, potassium sulfide."),
            ("Write the formula for strontium iodide and name it.",
             "Solution: SrI₂; strontium iodide."),
            ("Why is the formula for the compound of Mg²⁺ and N³⁻ Mg₃N₂ rather than MgN?",
             "Solution: Total positive charge must equal total negative charge. 3 Mg²⁺ (+6) balance 2 N³⁻ (−6); MgN would be unbalanced."),
        ],
        "Type II (Variable-Charge) Binary Ionic": [
            ("Name: FeCl₂, FeCl₃, CuO, Cu₂O, PbO₂.",
             "Solution: iron(II) chloride, iron(III) chloride, copper(II) oxide, copper(I) oxide, lead(IV) oxide."),
            ("Write formulas: (a) tin(II) fluoride, (b) tin(IV) fluoride, (c) iron(II) sulfide.",
             "Solution: (a) SnF₂, (b) SnF₄, (c) FeS."),
            ("Name CrCl₃ and CrCl₂.",
             "Solution: Chromium(III) chloride; chromium(II) chloride."),
            ("Determine the charge on Mn in MnO₂.",
             "Solution: Each O is −2; total −4. Mn must be +4. Compound name: manganese(IV) oxide."),
            ("Why must a Roman numeral appear in the name of FeCl₃ but not in NaCl?",
             "Solution: Iron forms more than one common cation (Fe²⁺, Fe³⁺), so the charge must be specified. Sodium has only one common ion (Na⁺), so no Roman numeral is needed."),
        ],
        "Polyatomic-Ion Compounds": [
            ("Name: NaNO₃, KOH, (NH₄)₂SO₄, Ca(OH)₂, K₂CO₃.",
             "Solution: Sodium nitrate, potassium hydroxide, ammonium sulfate, calcium hydroxide, potassium carbonate."),
            ("Write formulas: (a) iron(III) sulfate, (b) ammonium phosphate, (c) magnesium nitrate.",
             "Solution: (a) Fe₂(SO₄)₃, (b) (NH₄)₃PO₄, (c) Mg(NO₃)₂."),
            ("Distinguish sulfate from sulfite by formula.",
             "Solution: Sulfate = SO₄²⁻ (more O); sulfite = SO₃²⁻ (one less O). Same charge, different name (“-ate” vs “-ite”)."),
            ("Name K₂Cr₂O₇.",
             "Solution: Potassium dichromate (Cr₂O₇²⁻ is dichromate)."),
            ("Write the formula for copper(II) hydroxide and aluminum nitrate.",
             "Solution: Cu(OH)₂; Al(NO₃)₃."),
        ],
        "Binary Molecular": [
            ("Name: CO, CO₂, NO, NO₂, N₂O, SF₆.",
             "Solution: Carbon monoxide, carbon dioxide, nitrogen monoxide (nitric oxide), nitrogen dioxide, dinitrogen monoxide (nitrous oxide), sulfur hexafluoride."),
            ("Write formulas: (a) phosphorus pentachloride, (b) dinitrogen tetroxide, (c) tetraphosphorus decoxide.",
             "Solution: (a) PCl₅, (b) N₂O₄, (c) P₄O₁₀."),
            ("Name S₂Cl₂ and Cl₂O₇.",
             "Solution: Disulfur dichloride; dichlorine heptoxide."),
            ("Why is CO named carbon monoxide rather than monocarbon monoxide?",
             "Solution: The prefix “mono-” is dropped on the first element by convention; only the second element keeps the prefix when it would be “mono-”."),
            ("Identify two common binary molecular compounds with widely used non-systematic names.",
             "Solution: H₂O (water, not “dihydrogen monoxide”) and NH₃ (ammonia, not “nitrogen trihydride”)."),
        ],
        "Acids": [
            ("Name as acids in aqueous solution: HCl, HBr, HI, HF, H₂S.",
             "Solution: Hydrochloric, hydrobromic, hydroiodic, hydrofluoric, hydrosulfuric acid."),
            ("Name as oxyacids: HNO₃, HNO₂, H₂SO₄, H₂SO₃, H₃PO₄.",
             "Solution: Nitric, nitrous, sulfuric, sulfurous, phosphoric acid."),
            ("Write formulas for: hypochlorous acid, chloric acid, perchloric acid.",
             "Solution: HClO (hypo- + -ous), HClO₃ (-ic), HClO₄ (per- + -ic)."),
            ("Translate H₂CO₃(aq) into a name and explain the rule used.",
             "Solution: Carbonic acid. From CO₃²⁻ (carbonate, “-ate”): -ate → -ic acid."),
            ("Distinguish a binary acid from an oxyacid by composition and naming pattern.",
             "Solution: Binary acid: two elements (H + nonmetal); name uses “hydro- + root + -ic acid.” Oxyacid: H + polyatomic anion containing O; name uses “root + -ic” (from -ate) or “root + -ous” (from -ite)."),
        ],
        "Mixed practice": [
            ("Name: Mg(NO₃)₂, Cu(OH)₂, P₂O₅, HBr(aq), CaSO₄.",
             "Solution: Magnesium nitrate; copper(II) hydroxide; diphosphorus pentoxide; hydrobromic acid; calcium sulfate."),
            ("Write formulas: (a) potassium permanganate, (b) iron(III) carbonate, (c) ammonium chloride, (d) sulfur trioxide, (e) hydrocyanic acid.",
             "Solution: (a) KMnO₄, (b) Fe₂(CO₃)₃, (c) NH₄Cl, (d) SO₃, (e) HCN(aq)."),
            ("Classify each as Type I ionic, Type II ionic, polyatomic-ion compound, binary molecular, or acid: NaF, FeBr₂, NH₄NO₃, P₄O₆, HClO₄(aq).",
             "Solution: NaF Type I; FeBr₂ Type II; NH₄NO₃ polyatomic; P₄O₆ binary molecular; HClO₄(aq) acid (perchloric acid)."),
            ("Name CCl₄ and identify why no Roman numeral is used.",
             "Solution: Carbon tetrachloride. CCl₄ is a binary molecular compound (two nonmetals), so Greek prefixes — not Roman numerals — are used."),
            ("Provide names: Mn₂O₃, Sn(NO₃)₄, HF(aq).",
             "Solution: Manganese(III) oxide; tin(IV) nitrate; hydrofluoric acid."),
        ],
    },

    "08": {
        "Formula Mass and Mass Percent": [
            ("Compute the formula mass of NaCl. (Na 22.99, Cl 35.45.)",
             "Solution: 22.99 + 35.45 = 58.44 u (or g/mol)."),
            ("Compute the formula mass of Ca(OH)₂. (Ca 40.08, O 16.00, H 1.008.)",
             "Solution: 40.08 + 2(16.00 + 1.008) = 40.08 + 34.02 = 74.10 g/mol."),
            ("Compute the molar mass of glucose, C₆H₁₂O₆.",
             "Solution: 6(12.01) + 12(1.008) + 6(16.00) = 72.06 + 12.10 + 96.00 = 180.16 g/mol."),
            ("Compute the % nitrogen by mass in NH₃.",
             "Solution: M(NH₃) = 14.01 + 3(1.008) = 17.03 g/mol; %N = 14.01/17.03 × 100% = 82.27%."),
            ("Compute the % oxygen by mass in CaCO₃.",
             "Solution: M = 40.08 + 12.01 + 3(16.00) = 100.09 g/mol; %O = 48.00/100.09 × 100% = 47.96%."),
        ],
        "Mole Concept Conversions": [
            ("How many moles in 25.0 g of NaCl? (M = 58.44 g/mol.)",
             "Solution: 25.0 / 58.44 = 0.428 mol."),
            ("Mass, in grams, of 0.250 mol H₂O? (M = 18.02 g/mol.)",
             "Solution: 0.250 × 18.02 = 4.51 g."),
            ("Number of molecules in 0.100 mol CO₂?",
             "Solution: 0.100 × 6.022 × 10²³ = 6.022 × 10²² molecules."),
            ("Number of moles in 1.50 × 10²⁴ atoms of Ar?",
             "Solution: 1.50 × 10²⁴ / 6.022 × 10²³ = 2.49 mol."),
            ("Mass of 3.011 × 10²³ atoms of Cu? (M = 63.55 g/mol.)",
             "Solution: n = 3.011 × 10²³ / 6.022 × 10²³ = 0.500 mol; m = 0.500 × 63.55 = 31.78 g → 31.8 g."),
        ],
        "Mole Ratios from Formulas": [
            ("In Al₂(SO₄)₃, give the mole ratio of Al to S to O atoms.",
             "Solution: 2 : 3 : 12."),
            ("How many moles of H atoms in 0.50 mol C₆H₁₂O₆?",
             "Solution: 0.50 × 12 = 6.0 mol H."),
            ("How many moles of O atoms in 1.5 mol Mg(NO₃)₂?",
             "Solution: 1.5 × 6 = 9.0 mol O."),
            ("If 2.00 mol of (NH₄)₂SO₄ is dissolved, how many moles of N, H, S, O atoms?",
             "Solution: 4.00 mol N (2 × 2); 16.00 mol H (8 × 2); 2.00 mol S; 8.00 mol O."),
            ("How many H atoms in 18.0 g H₂O? (M = 18.02 g/mol.)",
             "Solution: n(H₂O) = 18.0/18.02 = 0.999 mol; n(H) = 2 × 0.999 = 1.998 mol; N(H) = 1.998 × 6.022 × 10²³ = 1.20 × 10²⁴ atoms."),
        ],
        "Empirical and Molecular Formulas": [
            ("A compound is 75.0% C and 25.0% H by mass. Find the empirical formula.",
             "Solution: Per 100 g: 75.0/12.01 = 6.245 mol C; 25.0/1.008 = 24.80 mol H. Ratio H/C = 24.80/6.245 = 3.97 ≈ 4. Empirical formula: CH₄."),
            ("A compound contains 27.3% C and 72.7% O by mass. Find the empirical formula.",
             "Solution: 27.3/12.01 = 2.273 mol C; 72.7/16.00 = 4.544 mol O. Ratio O/C = 2.00. Empirical formula: CO₂."),
            ("A 50.0 g sample contains 10.5 g N, 6.0 g H, and 24.0 g O, plus 9.5 g S. Find the empirical formula.",
             "Solution: 10.5/14.01 = 0.749 N; 6.0/1.008 = 5.95 H; 24.0/16.00 = 1.50 O; 9.5/32.06 = 0.296 S. Smallest = 0.296 S. Ratios: N 0.749/0.296 = 2.53; H 5.95/0.296 = 20.1; O 1.50/0.296 = 5.07; S 1. Multiply by 2 to clear fractions → N₅H₄₀O₁₀S₂; check: more reasonable to redo. Conclude: composition consistent with (NH₄)₂SO₄ if we recompute (N 2, H 8, S 1, O 4 expected). Sample composition does not exactly fit (NH₄)₂SO₄ — indicate that empirical formula is sensitive to mass-percent precision."),
            ("A compound has empirical formula CH₂O and molar mass 180 g/mol. Find the molecular formula.",
             "Solution: M(CH₂O) = 12.01 + 2(1.008) + 16.00 = 30.03; ratio = 180/30.03 = 6. Molecular formula: C₆H₁₂O₆ (glucose)."),
            ("A compound has empirical formula NO₂ and molar mass 92 g/mol. Find the molecular formula.",
             "Solution: M(NO₂) = 14.01 + 32.00 = 46.01; ratio = 92/46.01 = 2.00. Molecular formula: N₂O₄."),
        ],
        "Combustion analysis": [
            ("A 1.000 g sample of a hydrocarbon yields 3.143 g CO₂ and 1.286 g H₂O on combustion. Find the empirical formula.",
             "Solution: g C = 3.143 × (12.01/44.01) = 0.858 g; g H = 1.286 × (2.016/18.02) = 0.144 g; sum = 1.002 g (≈ 1.000 g). Mol C = 0.858/12.01 = 0.0714; mol H = 0.144/1.008 = 0.143. Ratio H/C = 2.00 → CH₂."),
            ("A 0.500 g hydrocarbon gives 1.571 g CO₂ and 0.643 g H₂O. Find empirical formula.",
             "Solution: C: 1.571 × (12.01/44.01) = 0.4287 g → 0.0357 mol; H: 0.643 × (2.016/18.02) = 0.0719 g → 0.0714 mol. Ratio H/C ≈ 2 → CH₂."),
            ("Combustion of 4.50 g of a compound containing C, H, and O gives 6.60 g CO₂ and 2.70 g H₂O. Find empirical formula.",
             "Solution: C: 6.60 × 12.01/44.01 = 1.802 g → 0.150 mol. H: 2.70 × 2.016/18.02 = 0.302 g → 0.300 mol. Mass O = 4.50 − 1.802 − 0.302 = 2.396 g → 0.150 mol. Ratios C:H:O = 0.150:0.300:0.150 = 1:2:1 → CH₂O."),
            ("Why must combustion analysis assume the compound contains C, H, and possibly O (and the O is found by difference)?",
             "Solution: Combustion measures C and H (as CO₂ and H₂O). It cannot directly detect O in the original compound. Mass not accounted for as C or H is attributed to O."),
            ("Combustion of 1.20 g of an unknown C–H compound gives 3.770 g CO₂. What % carbon by mass in the compound?",
             "Solution: g C = 3.770 × 12.01/44.01 = 1.029 g; %C = 1.029/1.20 × 100% = 85.7%."),
        ],
        "Purity": [
            ("A 5.00 g sample contains 4.50 g NaCl. What is the % purity?",
             "Solution: 4.50/5.00 × 100% = 90.0%."),
            ("A 25.0 g sample of an ore contains 6.25 g Fe. What is the mass-percent iron?",
             "Solution: 6.25/25.0 × 100% = 25.0%."),
            ("A drug tablet labeled 200 mg of acetaminophen tests at 196 mg actual. What is the % purity (with respect to the label)?",
             "Solution: 196/200 × 100% = 98.0%."),
            ("How many grams of pure NaCl are in 50.0 g of a sample 95.0% pure?",
             "Solution: 0.950 × 50.0 = 47.5 g."),
            ("A 10.0 g impure sample of CaCO₃ yields 4.00 g CO₂ on heating. M(CaCO₃) = 100.09 and M(CO₂) = 44.01. What % CaCO₃ in the sample?",
             "Solution: n(CO₂) = 4.00/44.01 = 0.0909 mol; n(CaCO₃) decomposed = 0.0909 mol; mass = 9.10 g. %CaCO₃ = 9.10/10.0 × 100% = 91.0%."),
        ],
        "Mixed": [
            ("A compound is 40.00% C, 6.71% H, 53.29% O. Molar mass 180.16 g/mol. Find the molecular formula.",
             "Solution: 40.00/12.01 = 3.331 C; 6.71/1.008 = 6.66 H; 53.29/16.00 = 3.331 O. Ratio 1:2:1 → CH₂O. M(CH₂O) = 30.03; 180.16/30.03 = 6 → C₆H₁₂O₆."),
            ("Compute the number of atoms in 1.0 g of carbon-12.",
             "Solution: 1.0/12.00 = 0.0833 mol; × 6.022 × 10²³ = 5.0 × 10²² atoms."),
            ("A 25.0 g sample of a compound contains 8.00 g of oxygen. What is the % oxygen?",
             "Solution: 8.00/25.0 × 100% = 32.0%."),
            ("Compute the mass of 2.50 × 10²³ molecules of N₂. (M = 28.02 g/mol.)",
             "Solution: n = 2.50 × 10²³ / 6.022 × 10²³ = 0.4151 mol; mass = 0.4151 × 28.02 = 11.63 g."),
            ("How many moles of H atoms are in 0.20 mol of (NH₄)₂CO₃?",
             "Solution: 8 H per formula unit × 0.20 mol = 1.6 mol H."),
        ],
    },

    "09": {
        "Balancing Equations": [
            ("Balance: H₂ + O₂ → H₂O.",
             "Solution: 2 H₂ + O₂ → 2 H₂O."),
            ("Balance: Al + O₂ → Al₂O₃.",
             "Solution: 4 Al + 3 O₂ → 2 Al₂O₃."),
            ("Balance: C₃H₈ + O₂ → CO₂ + H₂O.",
             "Solution: C₃H₈ + 5 O₂ → 3 CO₂ + 4 H₂O."),
            ("Balance: Fe₂O₃ + CO → Fe + CO₂.",
             "Solution: Fe₂O₃ + 3 CO → 2 Fe + 3 CO₂."),
            ("Balance: NH₃ + O₂ → NO + H₂O.",
             "Solution: 4 NH₃ + 5 O₂ → 4 NO + 6 H₂O."),
        ],
        "Reaction Classification": [
            ("Classify: 2 Na + Cl₂ → 2 NaCl.",
             "Solution: Combination (synthesis); also a redox reaction (Na → Na⁺, Cl₂ → 2 Cl⁻)."),
            ("Classify: 2 H₂O₂ → 2 H₂O + O₂.",
             "Solution: Decomposition; also redox."),
            ("Classify: Zn + 2 HCl → ZnCl₂ + H₂.",
             "Solution: Single-displacement (Zn displaces H); redox."),
            ("Classify: AgNO₃ + NaCl → AgCl + NaNO₃.",
             "Solution: Double-displacement (precipitation); not redox."),
            ("Classify: CH₄ + 2 O₂ → CO₂ + 2 H₂O.",
             "Solution: Combustion (and a combination reaction with O₂); redox."),
        ],
        "Mole-to-mole and mole-to-mass Stoichiometry": [
            ("For 2 H₂ + O₂ → 2 H₂O, how many moles of H₂O from 5.0 mol H₂ (excess O₂)?",
             "Solution: 5.0 mol H₂ × (2 mol H₂O / 2 mol H₂) = 5.0 mol H₂O."),
            ("For N₂ + 3 H₂ → 2 NH₃, how many moles of H₂ needed for 4.00 mol N₂?",
             "Solution: 4.00 mol N₂ × (3 mol H₂ / 1 mol N₂) = 12.0 mol H₂."),
            ("For 2 Al + 3 Cl₂ → 2 AlCl₃, mass of AlCl₃ produced from 0.500 mol Al? (M(AlCl₃) = 133.34.)",
             "Solution: 0.500 mol Al × (2/2) = 0.500 mol AlCl₃; mass = 0.500 × 133.34 = 66.67 g."),
            ("For CaCO₃ → CaO + CO₂, mass of CO₂ produced from 2.00 mol CaCO₃? (M(CO₂) = 44.01.)",
             "Solution: 2.00 mol CaCO₃ × (1/1) = 2.00 mol CO₂; mass = 2.00 × 44.01 = 88.0 g."),
            ("For 4 Fe + 3 O₂ → 2 Fe₂O₃, moles of O₂ needed to react with 0.200 mol Fe?",
             "Solution: 0.200 mol Fe × (3 mol O₂ / 4 mol Fe) = 0.150 mol O₂."),
        ],
        "Mass-to-mass Stoichiometry": [
            ("For 2 H₂ + O₂ → 2 H₂O, mass of water from 8.00 g H₂? (M(H₂) = 2.016, M(H₂O) = 18.02.)",
             "Solution: n(H₂) = 8.00/2.016 = 3.97 mol; n(H₂O) = 3.97 mol; m = 3.97 × 18.02 = 71.5 g."),
            ("For 2 Mg + O₂ → 2 MgO, mass of MgO from 12.0 g Mg? (M(Mg) = 24.31, M(MgO) = 40.30.)",
             "Solution: n(Mg) = 12.0/24.31 = 0.4937 mol; n(MgO) = 0.4937 mol; m = 0.4937 × 40.30 = 19.9 g."),
            ("For C₃H₈ + 5 O₂ → 3 CO₂ + 4 H₂O, mass of CO₂ from 22.0 g C₃H₈? (M(C₃H₈) = 44.10, M(CO₂) = 44.01.)",
             "Solution: n(C₃H₈) = 22.0/44.10 = 0.499 mol; n(CO₂) = 3 × 0.499 = 1.497 mol; m = 1.497 × 44.01 = 65.9 g."),
            ("For 2 KClO₃ → 2 KCl + 3 O₂, mass of O₂ from 5.00 g KClO₃? (M(KClO₃) = 122.55, M(O₂) = 32.00.)",
             "Solution: n(KClO₃) = 5.00/122.55 = 0.04080 mol; n(O₂) = 0.04080 × (3/2) = 0.0612 mol; m = 0.0612 × 32.00 = 1.96 g."),
            ("For N₂ + 3 H₂ → 2 NH₃, mass of NH₃ from 28.0 g N₂? (M(N₂) = 28.02, M(NH₃) = 17.03.)",
             "Solution: n(N₂) = 28.0/28.02 = 0.9993 mol; n(NH₃) = 2 × 0.9993 = 1.999 mol; m = 1.999 × 17.03 = 34.0 g."),
        ],
        "Theoretical, actual, percent yield": [
            ("In a reaction the theoretical yield is 25.0 g and the actual yield is 22.5 g. Compute % yield.",
             "Solution: 22.5/25.0 × 100% = 90.0%."),
            ("If a reaction has 78.0% yield and theoretical mass 4.50 g, what is the actual yield?",
             "Solution: 0.780 × 4.50 = 3.51 g."),
            ("A reaction yielded 14.0 g of product, theoretical = 17.5 g. % yield?",
             "Solution: 14.0/17.5 × 100% = 80.0%."),
            ("Why is actual yield usually less than theoretical yield?",
             "Solution: Side reactions, incomplete reaction, mechanical losses (transferring product), and impurities all reduce actual yield below the stoichiometric maximum."),
            ("For 2 Na + Cl₂ → 2 NaCl, calculate theoretical mass of NaCl from 4.60 g Na (excess Cl₂). M(Na) = 22.99, M(NaCl) = 58.44.",
             "Solution: n(Na) = 4.60/22.99 = 0.2001 mol; n(NaCl) = 0.2001 mol; m = 0.2001 × 58.44 = 11.7 g (theoretical)."),
        ],
        "Limiting Reactant": [
            ("For N₂ + 3 H₂ → 2 NH₃, identify the limiting reactant from 1.0 mol N₂ and 4.0 mol H₂.",
             "Solution: From 1.0 mol N₂, need 3.0 mol H₂; available 4.0. From 4.0 mol H₂, need 4.0/3 = 1.33 mol N₂; available 1.0. N₂ limits."),
            ("Using the limiting reactant in the prior problem, how many moles of NH₃ are produced?",
             "Solution: 1.0 mol N₂ × (2/1) = 2.0 mol NH₃."),
            ("For 2 Al + 3 Cl₂ → 2 AlCl₃, identify limiting reactant from 0.50 mol Al and 0.50 mol Cl₂.",
             "Solution: 0.50 mol Al would need 0.75 mol Cl₂; only 0.50 available. So Cl₂ limits."),
            ("Using the limiting reactant from the prior problem, mass of AlCl₃ produced? (M = 133.34.)",
             "Solution: n(AlCl₃) = 0.50 mol Cl₂ × (2/3) = 0.333 mol; m = 0.333 × 133.34 = 44.4 g."),
            ("How much excess reactant remains unconsumed (in moles) in the prior problem?",
             "Solution: Al consumed = 0.50 mol Cl₂ × (2/3) = 0.333 mol; Al leftover = 0.50 − 0.333 = 0.167 mol."),
        ],
    },

    "10": {
        "KMT and States": [
            ("State the four central postulates of the kinetic-molecular theory for gases.",
             "Solution: (1) Gases consist of many small particles in random motion. (2) The volume of the particles is negligible compared with the volume of the container. (3) Particles exert no attractive or repulsive forces on each other. (4) Average kinetic energy of the particles is proportional to absolute temperature."),
            ("Explain why a gas exerts pressure on the walls of its container.",
             "Solution: Gas particles strike the walls; each collision transfers momentum. The total force per unit area from many such collisions per second is the pressure."),
            ("If the absolute temperature of a gas doubles, by what factor does the average kinetic energy change?",
             "Solution: Doubles. ⟨KE⟩ ∝ T."),
            ("Order solid, liquid, and gas by typical particle separation and order/disorder.",
             "Solution: Particle separation: solid ≲ liquid ≪ gas. Order: solid (most ordered) > liquid > gas (most disordered)."),
            ("Why are gases highly compressible and liquids essentially incompressible?",
             "Solution: Gas particles are widely separated, so the empty space can be compressed. Liquid particles are already in contact; further compression must overcome strong short-range repulsions."),
        ],
        "Crystal Types": [
            ("Identify the crystal type of each: NaCl, diamond, Cu, ice, dry ice (CO₂).",
             "Solution: NaCl ionic; diamond covalent network; Cu metallic; ice molecular (H-bonded); dry ice molecular."),
            ("Predict the relative melting points of an ionic crystal and a molecular crystal of similar molar mass.",
             "Solution: The ionic crystal melts much higher because Coulombic attractions among ions are far stronger than intermolecular forces in molecular solids."),
            ("Why are metals typically good electrical conductors in the solid state, while ionic crystals are not?",
             "Solution: Metals have a delocalized “sea” of valence electrons free to move; ionic solids have ions locked in lattice positions, so charges cannot flow. Molten ionic compounds, however, do conduct."),
            ("Explain why diamond is one of the hardest known substances.",
             "Solution: Each carbon atom is bonded covalently to four neighbors in a 3D network. Deforming the crystal requires breaking strong directional covalent bonds throughout the structure."),
            ("A solid is brittle, has a high melting point, dissolves in water, and the solution conducts electricity. Identify the crystal type.",
             "Solution: Ionic. Brittleness, high m.p., water-solubility, and ionic conductivity in solution are signature properties."),
        ],
        "Liquid Properties": [
            ("Define surface tension and give an everyday example.",
             "Solution: Surface tension is the energy required to increase the surface area of a liquid (the inward pull on surface molecules). Example: water beads on a waxed surface; insects walk on water."),
            ("Compare the viscosity of water and honey, and link the difference to intermolecular forces.",
             "Solution: Honey is much more viscous. Honey contains sugars that form many hydrogen bonds among large molecules, increasing internal resistance to flow."),
            ("Explain capillary action in a thin glass tube of water.",
             "Solution: Adhesive forces between water and glass exceed cohesive forces among water molecules. Water climbs the tube against gravity until adhesion balances the weight of the column."),
            ("Why does water have a higher boiling point than methane (CH₄), although both have similar molar mass?",
             "Solution: Water hydrogen-bonds; methane has only weak London dispersion forces. Stronger intermolecular forces in water raise its boiling point dramatically."),
            ("Define vapor pressure of a liquid.",
             "Solution: The pressure exerted by the vapor in equilibrium with its liquid at a given temperature. It increases with temperature and depends on the strength of intermolecular forces."),
        ],
        "Intermolecular Forces": [
            ("Identify the dominant IMF in: CH₄, HF, CH₃OH, NaCl, Ne.",
             "Solution: CH₄ dispersion; HF hydrogen bonding (and dipole–dipole, dispersion); CH₃OH hydrogen bonding; NaCl ionic forces (not strictly an IMF — a solid lattice); Ne dispersion."),
            ("Rank in order of increasing boiling point: CH₄, CH₃OH, H₂O.",
             "Solution: CH₄ (−161 °C) < CH₃OH (65 °C) < H₂O (100 °C). Water hydrogen-bonds with two donors and two acceptors per molecule, beating methanol."),
            ("Explain why noble gas boiling points increase from He to Xe.",
             "Solution: Larger atoms have more electrons and more polarizable clouds, so London dispersion forces grow stronger down the group, raising boiling points."),
            ("Which has a higher boiling point: HBr or HCl? Explain.",
             "Solution: HBr. Both are dipole–dipole, but HBr has more electrons and larger dispersion forces, dominating the slightly larger H—X dipole of HCl."),
            ("Why is CHCl₃ a higher-boiling liquid than CH₄ of similar molar mass family?",
             "Solution: CHCl₃ has a permanent dipole (polar) and large dispersion forces from many electrons. CH₄ is nonpolar with much smaller dispersion forces."),
        ],
        "Vapor Pressure and Boiling": [
            ("Define the boiling point of a liquid in terms of vapor pressure.",
             "Solution: The temperature at which the liquid’s vapor pressure equals the external (atmospheric) pressure."),
            ("Why does water boil at a lower temperature on a high mountain?",
             "Solution: Atmospheric pressure is lower at altitude, so the vapor pressure required to match it is reached at a lower temperature."),
            ("Predict whether ethanol or water has the higher vapor pressure at 25 °C, given that ethanol’s boiling point (78 °C) is below water’s (100 °C).",
             "Solution: Ethanol. Lower boiling point means higher vapor pressure at any given temperature — ethanol’s intermolecular forces are weaker than water’s."),
            ("Explain why a pressure cooker speeds up cooking.",
             "Solution: Sealed pressure rises; water boils at a higher temperature (e.g., ≈120 °C at 2 atm). Hotter water cooks foods faster."),
            ("If a liquid’s vapor pressure at 50 °C is 250 mmHg, will it boil at 50 °C and standard atmospheric pressure (760 mmHg)? Explain.",
             "Solution: No. Boiling occurs only when vapor pressure equals atmospheric pressure (760 mmHg). At 50 °C the vapor pressure is far below that, so it only evaporates."),
        ],
        "Specific Heat": [
            ("How much heat is required to raise 100.0 g of water from 25.0 °C to 75.0 °C? (c = 4.184 J/g·°C.)",
             "Solution: q = mcΔT = 100.0 × 4.184 × 50.0 = 20920 J = 20.9 kJ."),
            ("A 50.0 g block of metal absorbs 1.20 kJ as it heats from 20.0 to 84.0 °C. Compute c.",
             "Solution: c = q/(mΔT) = 1200 J / (50.0 × 64.0 °C) = 0.375 J/g·°C."),
            ("Why does water make a good coolant?",
             "Solution: Water has an unusually high specific heat (4.184 J/g·°C) and high heat of vaporization, so it absorbs a great deal of heat per gram for modest temperature change."),
            ("How many joules to raise the temperature of 250 g of aluminum (c = 0.897 J/g·°C) by 30.0 °C?",
             "Solution: q = 250 × 0.897 × 30.0 = 6728 J ≈ 6.73 kJ."),
            ("If 500.0 J is added to 25.0 g of copper (c = 0.385 J/g·°C) at 22.0 °C, what is the final T?",
             "Solution: ΔT = q/(mc) = 500/(25.0 × 0.385) = 51.95 °C; T_f = 22.0 + 51.95 = 73.95 °C ≈ 74.0 °C."),
        ],
        "Anomalies of Water": [
            ("State two ways in which water’s solid form (ice) is anomalous compared with most substances.",
             "Solution: (1) Ice is less dense than liquid water, so it floats. (2) Most solids are denser than their liquid forms; ice’s open hydrogen-bonded lattice is the exception."),
            ("Why is the density anomaly of water important for aquatic life?",
             "Solution: Ice forms a floating insulating layer. Liquid water at 4 °C (its maximum density) sinks below the ice, allowing aquatic organisms to survive winter at the bottom."),
            ("Why does water have such a high boiling point compared with H₂S, H₂Se, and H₂Te?",
             "Solution: Hydrogen bonding. The strong O—H ··· O network in water requires much more energy to disrupt than the dipole–dipole + dispersion forces in heavier-chalcogen hydrides."),
            ("Explain why water has unusually high specific heat compared with most liquids.",
             "Solution: A large fraction of input energy goes into stretching/breaking hydrogen bonds and increasing molecular motion within the H-bonded network, not just translational kinetic energy."),
            ("Why is hot water poured on ice an effective de-icer in some situations but not in very cold weather?",
             "Solution: Hot water transfers heat to melt ice quickly. In very cold weather (well below 0 °C), the meltwater quickly refreezes, often producing a more dangerous slick of fresh ice."),
        ],
    },
}
